parameters:
    app_back_office.esconfig_manager.class: App\Bundle\BackOfficeBundle\DependencyInjection\Services\ConfigManagerService

services:
    esconfig_manager:
        class: %app_back_office.esconfig_manager.class%
        arguments: []
        calls:
            - [setContainer,[@service_container]]


#    app_back_office.example:
#        class: %app_back_office.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
