imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBackOfficeBundle, AppFrontOfficeBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   conescol
        connections:
            conescol:
                dbname:               %database_name%
                host:                 %database_host%
                port:                 %database_port%
                user:                 %database_user%
                password:             %database_password%
                driver:               %database_driver%
                charset:              UTF8
                logging:              %kernel.debug%
    orm:
        auto_generate_proxy_classes:    true
        proxy_namespace:                Proxies
        proxy_dir:                      %kernel.cache_dir%/doctrine/orm/Proxies
        default_entity_manager:         escoorm
        entity_managers:
            escoorm:
                # The name of a DBAL connection (the one marked as default is used if not set)
                connection:         conescol
                mappings: # Required
                    AppBackOfficeBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
