escolarite:
    date_format: d-m-Y
    datetime_format: 'd-m-Y\TH:i'
    current_semester: 1
    current_academic_year: 2013
    activate_service: yes
    auto_demands_answers:
        status: activate
        amount: 5
