app_front_office_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AppFrontOfficeBundle:Default:index }

rendezvous:
    pattern:  /demande/rendezvous
    defaults: { _controller: AppFrontOfficeBundle:Demande:rendezvous }
    
    
demandepiece:
    pattern:  /demande/demandepiece
    defaults: { _controller: AppFrontOfficeBundle:Demande:demandepiece }

changer:
    pattern:  /changement

    defaults: { _controller: AppFrontOfficeBundle:Changement:changer }
    
reclamationEtud:
    pattern: /reclamation
    defaults: { _controller: AppFrontOfficeBundle:Reclamation:envoyer }

listerReclamationEtud:
    pattern: /listerReclamation
    defaults: { _controller: AppFrontOfficeBundle:Reclamation:index }

showReclamationEtud:
    pattern: /{id}/showReclamation
    defaults: { _controller: AppFrontOfficeBundle:Reclamation:show }

showDemandeEtud:
    pattern: /demande/{id}/show
    defaults: { _controller: AppFrontOfficeBundle:Demande:show }

front_login:
    pattern: /login
    defaults: { _controller: AppFrontOfficeBundle:SecurityPointAccess:login }

front_login_check:
    pattern:   /login_check
    
front_logout:
    path:   /logout

ElemRef:
    pattern: /Elemref
    defaults: { _controller: AppFrontOfficeBundle:Elemref:index }

test:
    path: /test
    defaults: { _controller: AppFrontOfficeBundle:Demande:test }

consulterElemRef:
    pattern:  /consulter/{id}
    defaults: { _controller: "AppFrontOfficeBundle:ElemRef:show" }

ElemRefEstEnvoye:
    pattern: /ElemRefEnvoye
    defaults: { _controller: AppFrontOfficeBundle:ElemRef:estEnvoye }
