module_libre:
    pattern: /verifAuto
    defaults: { _controller: AppFrontOfficeBundle:ModuleLibre:module5 }

demande-module-libre:
    pattern:  /demandemodulelibre
    defaults: { _controller: AppFrontOfficeBundle:ModuleLibre:EnvoyerDemandeModule5 }

consulter5Module:
    pattern:  /consulterMod5/{id}
    defaults: { _controller: AppFrontOfficeBundle:ModuleLibre:show }