<?php

namespace App\Bundle\BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends EntityRepository
{
	public function getLastReponceDate()
	{
		
		$qb = $this->createQueryBuilder("d")->
		select ("max(d.dateReponce)")->getQuery();
		$resutls=$qb->getResult();
		return $resutls[0][1];
	}
	
}
