<?php

namespace App\Bundle\BackOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{
	public function deleteAll(){
		$this->getEntityManager()->createQuery("delete from AppBackOfficeBundle:Etudiant")->execute();
	}
}
